const test=require('node:test'),assert=require('node:assert/strict');
const P=require('../src/package-xml'),Z=require('../src/docxZip'),D=require('../src/docx-media'),N=require('../src/registered-native'),Match=require('../src/design-matching');
const png=(w,h)=>{const b=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(b);b.writeUInt32BE(13,8);b.write('IHDR',12);b.writeUInt32BE(w,16);b.writeUInt32BE(h,20);return b;};
const drawing=id=>`<w:drawing><wp:inline><a:blip r:embed="${id}"/></wp:inline></w:drawing>`;
function word(body,rels){return P.zip([['word/document.xml',`<w:document><w:body><w:p><w:r><w:t>제목</w:t></w:r></w:p>${body}<w:p><w:r><w:t>본문입니다.</w:t></w:r></w:p></w:body></w:document>`],['word/_rels/document.xml.rels',`<Relationships>${rels}</Relationships>`],['word/media/a.png',png(1200,800)],['word/media/b.png',png(600,900)],['word/media/unused.png',png(1,1)]]);}
const rel=(id,name)=>`<Relationship Id="${id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/${name}"/>`;
test('DOCX relationships determine image order, dimensions and profile; unused resources excluded',()=>{const out=D.extract(word(`<w:p>${drawing('b')}</w:p><w:p>${drawing('a')}</w:p>`,rel('a','a.png')+rel('b','b.png')));assert.deepEqual(out.article.images.map(i=>i.originalName),['b.png','a.png']);assert.equal(out.article.images[0].orientation,'portrait');assert.equal(out.article.images[1].aspectRatio,1.5);const profile=Match.articleProfile(out.article);assert.equal(profile.imageCount,2);assert.equal(profile.images[0].paragraphPosition,1);});
test('duplicate relationships to same image retain occurrence positions without duplicate photos',()=>{const out=D.extract(word(`<w:p>${drawing('a')}${drawing('alias')}</w:p>`,rel('a','a.png')+rel('alias','a.png')));assert.equal(out.article.images.length,1);assert.equal(out.article.images[0].occurrences.length,2);});
test('explicit decorative/background images excluded with warning',()=>{const out=D.extract(word(`<w:p><w:drawing><wp:anchor behindDoc="1"><a:blip r:embed="a"/></wp:anchor></w:drawing></w:p>`,rel('a','a.png')));assert.equal(out.article.images.length,0);assert.equal(out.warnings.length,1);});
test('ambiguous duplicate relationship IDs and escaping paths rejected',()=>{assert.throws(()=>D.extract(word(`<w:p>${drawing('a')}</w:p>`,rel('a','a.png')+rel('a','b.png'))),/중복/);for(const p of ['../secret','file:///secret','../../media/a.png'])assert.throws(()=>D.target(p));});
test('stored package CRC, UTF8 and XML namespace escaping roundtrip',()=>{const xml=P.serialize({tag:'{urn:test}root',attributes:{name:'한글 & "'},text:'<본문>\r',children:[]});assert.match(xml,/xmlns:ns0="urn:test"/);assert.match(xml,/&amp;/);const bytes=P.zip([['mimetype','application/test'],['test.xml',xml]]);assert.equal(Z.utf8BytesToString(Z.readZipEntry(bytes,'test.xml')),xml);assert.equal(P.crc(Buffer.from('123456789')),0xcbf43926);assert.throws(()=>P.zip([['../escape','x']]));});
test('Fidelity failure remains blocking and forbids false output success',()=>{const ID={app:{scriptPreferences:{measurementUnit:'mm'}},MeasurementUnits:{POINTS:'pt'}};const issues=N.check({phase:'FIDELITY_FAILED',contentChecks:[]},ID);assert.equal(issues[0].cause,'GENERATOR_MISMATCH');assert.equal(issues[0].category,'BLOCKING');assert.equal(ID.app.scriptPreferences.measurementUnit,'mm');});
test('content geometry drift classified as fidelity failure, not content fit',()=>{const ID={app:{scriptPreferences:{measurementUnit:'mm'}},MeasurementUnits:{POINTS:'pt'}};const c={phase:'CONTENT_APPLIED',contentChecks:[{role:'image1',bounds:[0,0,10,10],frame:{parentPage:{bounds:[0,0,100,100]},geometricBounds:[0,0,11,10]}}]};assert.equal(N.check(c,ID)[0].cause,'GENERATOR_MISMATCH');});
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process'),R=require('../src/design-registration'),M=require('../src/design-model');
const py=path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe');
const result=spawnSync(fs.existsSync(py)?py:'python3',['tests/test_design_extraction.py','--model'],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);
function fixture(){const m=JSON.parse(result.stdout),base=m.elements[0],s=m.stories.find(s=>s.id===base.textFrame.storyRef);for(const r of s.paragraphs.flatMap(p=>p.runs))r.resolvedProperties=JSON.parse(JSON.stringify(s.paragraphs[0].runs[0].resolvedProperties));const body=JSON.parse(JSON.stringify(base)),bs=JSON.parse(JSON.stringify(s));body.id='body';body.role.confirmed=null;body.textFrame.storyRef='bodyStory';body.pageBounds.p1=[150,20,700,420];bs.id='bodyStory';m.elements.push(body);m.stories.push(bs);const d=R.draft(m,'p1');R.confirm(d,'body','body');return R.register(m,d);}
function host(entry,{drift=false,originalOverflow=false,contentOverflow=false}={}){const ID={MeasurementUnits:{POINTS:'pt'},app:{scriptPreferences:{measurementUnit:'mm'}},Leading:{AUTO:'auto'},Justification:Object.fromEntries(Object.values(M.ALIGN).map(k=>[k,k]))},frames=[];let recomposes=0;
const page={extractLabel:()=>entry.descriptor.pageIds[0],bounds:[0,0,entry.original.pages[0].height,entry.original.pages[0].width],allPageItems:frames};
for(const e of entry.original.elements){if(!e.textFrame)continue;const s=entry.original.stories.find(s=>s.id===e.textFrame.storyRef),runs=s.paragraphs.flatMap(p=>p.runs);let contents=runs.flatMap(r=>r.tokens.map(t=>t.type==='Content'?t.text:t.type==='Br'?'\r':'')).join('');const props=runs[0].resolvedProperties,t={appliedFont:{fontFamily:props.AppliedFont},fontStyle:props.FontStyle,justification:M.ALIGN[props.Justification],fillColor:'black',appliedCharacterStyle:'char'};for(const [k,v] of Object.entries({...M.TYPE,...M.PARA}))if(props[k]!==undefined)t[v]=props[k];Object.defineProperty(t,'contents',{get:()=>contents});const story={get contents(){return contents;},set contents(v){contents=v;},get overflows(){return contents==='새 본문'&&contentOverflow;},characters:{item:()=>t,itemByRange:(a,b)=>({...t,contents:contents.slice(a,b+1)})},paragraphs:{item:()=>({appliedParagraphStyle:'para'})},texts:{item:()=>t}};
const prefs=Match.framePreferences(entry.original,e).effective;frames.push({extractLabel:()=>e.id,parentPage:page,geometricBounds:e.pageBounds.p1.map((x,i)=>x+(drift&&i===0?1:0)),parentStory:story,textFramePreferences:{textColumnCount:prefs.TextColumnCount,textColumnGutter:prefs.TextColumnGutter,insetSpacing:prefs.InsetSpacing}});}
const doc={pages:[page],spreads:[{}],recompose(){recomposes++;},allPageItems:frames};return {ID,doc,frames,env:{ID,open:async()=>doc,guard(){},inspect:()=>({errors:originalOverflow?['source overflow']:[]})},get recomposes(){return recomposes;}};}
test('native pipeline compares original first, replaces uniform text, retains original model and bounds',async()=>{const entry=fixture(),before=JSON.stringify(entry.original),h=host(entry),c=await N.create(entry,{title:'새 제목',body:'새 본문',images:[]},h.env);assert.equal(c.phase,'CONTENT_APPLIED');assert.equal(h.recomposes,2);assert.equal(N.check(c,h.ID).length,0);assert.equal(JSON.stringify(entry.original),before);assert.equal(h.frames.find(f=>f.extractLabel()==='body').parentStory.contents,'새 본문');});
test('source mismatch or original overflow leaves content untouched and blocks output',async()=>{for(const option of [{drift:true},{originalOverflow:true}]){const entry=fixture(),h=host(entry,option),text=h.frames[0].parentStory.contents,c=await N.create(entry,{title:'새 제목',body:'새 본문',images:[]},h.env);assert.equal(c.phase,'FIDELITY_FAILED');assert.equal(c.autoFixAllowed,false);assert.equal(h.frames[0].parentStory.contents,text);assert.ok(N.check(c,h.ID).length);}});
test('post replacement overflow is content issue, never silently auto-fitted',async()=>{const entry=fixture(),h=host(entry,{contentOverflow:true}),c=await N.create(entry,{title:'새 제목',body:'새 본문',images:[]},h.env);assert.equal(c.phase,'CONTENT_APPLIED');assert.equal(N.check(c,h.ID)[0].cause,'CONTENT_OVERFLOW');assert.equal(c.autoFixAllowed,false);});
test('stale open identifies only newly opened document for cleanup',async()=>{const entry=fixture(),h=host(entry);let calls=0;h.env.guard=()=>{if(++calls>1)throw new Error('reload');};await assert.rejects(()=>N.create(entry,{title:'새 제목',body:'새 본문',images:[]},h.env),e=>e.registeredDocument===h.doc);});
