'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Options=require('../src/registered-options'),Merge=require('../src/registered-options-host');
const job=n=>({article:{title:'DOCX',body:'text',images:[{path:'/docx.png'}]},selected:Array.from({length:n},(_,i)=>({optionId:'OPTION_'+(i+1),entry:{},descriptor:{id:'design-'+i,sourceSha256:'source',pageIds:['page']}}))});
const pass=()=>({errors:[],warnings:[],issues:[],outputReady:true,fidelity:{phase:'CONTENT_APPLIED'}});
function adapter(fail){const calls=[],closed=[];return {calls,closed,progress(){},async produce(entry,article){calls.push({id:entry.descriptor.id,article});if(fail===entry.descriptor.id)throw new Error('SOURCE_OVERFLOW');return {doc:{id:entry.descriptor.id},report:pass()};},close:d=>closed.push(d.id),async combine(made,rows){return {rows,doc:{},report:Options.report(rows,made.length)};}};}
test('all options use independent copies of the same DOCX and finish with one result',async()=>{const a=adapter(),j=job(3);const result=await Options.run(j,a);assert.equal(a.calls.length,3);assert.equal(result.report.outputReady,true);a.calls[0].article.images[0].path='changed';assert.equal(a.calls[1].article.images[0].path,'/docx.png');assert.equal(j.article.images[0].path,'/docx.png');});
test('one production exception does not stop later options; output stays blocked',async()=>{const a=adapter('design-1'),result=await Options.run(job(3),a);assert.equal(a.calls.length,3);assert.deepEqual(result.rows.map(r=>r.status),['PASS','BLOCK','PASS']);assert.equal(result.report.outputReady,false);assert.match(result.report.errors[0],/SOURCE_OVERFLOW/);});
test('content overflow and Fidelity failure are never counted as successful options',async()=>{const a=adapter();let count=0;a.produce=async()=>({doc:{id:++count},report:{...pass(),errors:[count===1?'SOURCE_OVERFLOW':'CONTENT_OVERFLOW'],outputReady:false}});const r=await Options.run(job(3),a);assert.equal(r.doc,null);assert.equal(a.closed.length,3);assert.ok(r.rows.every(r=>r.status==='BLOCK'));});
test('incomplete content replacement cannot pass just because there are no errors',async()=>{const a=adapter();a.produce=async()=>({doc:{},report:{...pass(),fidelity:{phase:'FIDELITY_PASSED'}}});const r=await Options.run(job(1),a);assert.equal(r.rows[0].status,'BLOCK');});
test('two candidates are not padded with BLOCK designs and cannot be exported',async()=>{const a=adapter(),r=await Options.run(job(2),a);assert.equal(a.calls.length,2);assert.equal(r.report.outputReady,false);assert.match(r.report.errors[0],/2\/3/);});
test('fatal combination closes all staging documents',async()=>{const a=adapter();a.combine=async()=>{throw new Error('UNSAFE');};await assert.rejects(Options.run(job(3),a),/UNSAFE/);assert.equal(a.closed.length,3);});
function entry(){return {descriptor:{id:'d',pageIds:['p']},original:{layers:[{properties:{Name:'Layer',Printable:true}}],sourceXml:{'Resources/Styles.xml':{name:'Body',size:10},'Resources/Graphic.xml':{name:'Accent',values:[0,0,0,10]},'Resources/Preferences.xml':{composer:'CJK'},'MasterSpreads/MasterSpread_m.xml':{numberMarker:'ACE 18'}}}};}
test('same name different style, Swatch, Parent, layer and document settings block before duplication',()=>{for(const key of ['Resources/Styles.xml','Resources/Graphic.xml','Resources/Preferences.xml','MasterSpreads/MasterSpread_m.xml']){const a=entry(),b=entry();b.original.sourceXml[key].changed=true;assert.throws(()=>Merge.compatibility(a,b),/OPTION_RESOURCE_CONFLICT/);}const a=entry(),b=entry();b.original.layers[0].properties.Printable=false;assert.throws(()=>Merge.compatibility(a,b));assert.doesNotThrow(()=>Merge.compatibility(a,a));});
function mergeDouble(breakCopy){
 let serial=0;const col=rows=>({length:rows.length,item:i=>rows[i]}),ref=o=>o?.source||null;
 function doc(count){const d={id:++serial,isValid:true,sp:[],masters:[{source:'master'}],get masterSpreads(){return col(this.masters);},get pages(){return col(this.sp.flatMap(s=>s.ps));},get spreads(){return col(this.sp);},recompose(){},insertLabel(){},close(){this.isValid=false;}};
  for(let i=0;i<count;i++)add(d,i);return d;}
 function add(d,index,src){const labels={...(src?.labels||{})},spread={id:++serial,source:'spread'+index,ps:[],remove(){d.sp.splice(d.sp.indexOf(this),1);},duplicate(where,target){return add(target,index,this.ps[0]);}};
  const p={source:'p'+index,bounds:[0,0,800,500],side:'RIGHT',parent:spread,appliedMaster:d.masters[0],labels,extractLabel:k=>labels[k]||'',insertLabel:(k,v)=>labels[k]=v,allPageItems:[{source:'frame',text:breakCopy&&src?'corrupted':'DOCX',image:'/docx.png',thread:['frame'],geometry:[1,2,3,4]}]};spread.ps=[p];d.sp.push(spread);return spread;}
 const F={ref,list:c=>Array.isArray(c)?c:Array.from({length:c.length},(_,i)=>c.item(i)),compare:(a,b)=>require('../src/design-model').compare(a,b),capture(d){return JSON.parse(JSON.stringify({pages:this.list(d.pages).map(p=>({id:ref(p),items:p.allPageItems}))}));}};
 const N={rebind:(c,d)=>{c.doc=d;},check:()=>[]};
 const sandbox={module:{exports:{}},require:n=>n==='./registered-fidelity'?F:n==='./registered-native'?N:n==='./registered-options'?Options:require('../src/design-model')};vm.runInNewContext(fs.readFileSync('src/registered-options-host.js','utf8'),sandbox);
 const made=(id,count)=>{const d=doc(count),e=entry();e.descriptor={...e.descriptor,id,pageIds:F.list(d.pages).map(ref)};return {doc:d,context:{entry:e,contentChecks:[]},report:pass(),row:{optionId:id,designId:id,sourceId:'same',pageIds:e.descriptor.pageIds,status:'PASS',errors:[],report:pass()}};};
 return {M:sandbox.module.exports,made,ID:{app:{scriptPreferences:{measurementUnit:'old'}},MeasurementUnits:{POINTS:'pt'},LocationOptions:{AT_END:1},SaveOptions:{NO:0}}};
}
test('whole page sets combine in order, duplicate source references remain OPTION-scoped',()=>{const h=mergeDouble(),made=[h.made('OPTION_1',1),h.made('OPTION_2',2),h.made('OPTION_3',1)],r=h.M.combine(made,made.map(m=>m.row),h.ID,()=>{});assert.equal(r.doc.pages.length,4);assert.equal(r.report.outputReady,true);assert.deepEqual(JSON.parse(JSON.stringify(r.rows.map(r=>r.pageRange))),[{start:1,end:1},{start:2,end:3},{start:4,end:4}]);assert.equal(made[1].doc.isValid,false);assert.equal(made[2].doc.isValid,false);assert.equal(h.ID.app.scriptPreferences.measurementUnit,'old');});
test('changed copied content rolls back only failed option and leaves output blocked',()=>{const h=mergeDouble(true),made=[h.made('OPTION_1',1),h.made('OPTION_2',1),h.made('OPTION_3',1)],r=h.M.combine(made,made.map(m=>m.row),h.ID,()=>{});assert.equal(r.doc.pages.length,1);assert.equal(r.report.outputReady,false);assert.deepEqual(r.rows.map(r=>r.status),['PASS','BLOCK','BLOCK']);});
test('scope rejects missing/ambiguous Parent or changed option page references',()=>{const h=mergeDouble(),made=h.made('OPTION_1',1),r=h.M.combine([made],[made.row],h.ID,()=>{});r.doc.masters.push({source:'master'});assert.throws(()=>h.M.check(r.batch,h.ID),/PARENT_REFERENCE/);r.doc.masters.pop();r.doc.pages.item(0).source='wrong';assert.throws(()=>h.M.check(r.batch,h.ID),/PAGE_REFERENCE/);});
test('post-merge check detects changed image/content/thread/geometry without reparsing DOCX',()=>{for(const property of ['text','image','thread','geometry']){const h=mergeDouble(),made=h.made('OPTION_1',1),r=h.M.combine([made],[made.row],h.ID,()=>{});r.doc.pages.item(0).allPageItems[0][property]=property==='thread'?['other']:property==='geometry'?[0,0,10,10]:'changed';const report=h.M.check(r.batch,h.ID);assert.equal(report.outputReady,false);assert.ok(report.errors.some(e=>e.includes('결합 전후')));}});


test('first option preparation failure does not prevent later successful page sets',()=>{const h=mergeDouble(),made=[h.made('OPTION_1',1),h.made('OPTION_2',1),h.made('OPTION_3',1)];made[0].doc.masters[0].source=null;const r=h.M.combine(made,made.map(m=>m.row),h.ID,()=>{});assert.equal(r.doc.pages.length,2);assert.deepEqual(r.rows.map(r=>r.status),['BLOCK','PASS','PASS']);assert.equal(r.report.outputReady,false);assert.equal(made[0].doc.isValid,false);});

test('Adobe duplicate Story label loss restores metadata only after exact content/thread/option evidence',()=>{
 const labels={},story={id:1,contents:'DOCX 본문',extractLabel:k=>labels[k]||'',insertLabel:(k,v)=>labels[k]=v};
 const frame={parentStory:story,parentPage:{extractLabel:()=> 'OPTION_2'},extractLabel:()=> 'body'};story.textContainers=[frame];const view={allPageItems:[frame]},snapshot={objects:{body:{storyRef:'sourceStory',story:'DOCX 본문',thread:['body']}}};
 Merge.restoreStoryReferences(view,snapshot,'OPTION_2');assert.equal(labels.MagazineStudioSourceRef,'sourceStory');assert.equal(story.contents,'DOCX 본문');
 for(const damage of ['contents','thread','option','label']){delete labels.MagazineStudioSourceRef;story.contents='DOCX 본문';story.textContainers=[frame];frame.parentPage.extractLabel=()=> 'OPTION_2';if(damage==='contents')story.contents='wrong';if(damage==='thread')story.textContainers=[];if(damage==='option')frame.parentPage.extractLabel=()=> 'OPTION_1';if(damage==='label')labels.MagazineStudioSourceRef='different';assert.throws(()=>Merge.restoreStoryReferences(view,snapshot,'OPTION_2'),/OPTION_/);assert.notEqual(labels.MagazineStudioSourceRef,'sourceStory');}
});
