const test=require('node:test'),assert=require('node:assert/strict'),A=require('../src/registered-auto-fit'),M=require('../src/design-model');
function fixture({role='body',threshold=.96,initial=false,autoLeading=false}={}){
 const chars=[{pointSize:initial?18:12,leading:autoLeading?'Auto':16,tracking:20},{pointSize:12,leading:autoLeading?'Auto':16,tracking:20}],story={contents:'가나',characters:{length:2,item:i=>chars[i]},get overflows(){return chars[1].pointSize>12*threshold+.00001;}};
 const c={role,frame:{parentStory:story},text:'가나',bounds:[0,0,100,100],typography:{PointSize:12,Leading:autoLeading?'Auto':16},textPolicy:{mode:initial?'enlarged-story-initial':'uniform'},overrides:{pointSize:12}},context={contentChecks:[c],contentWarnings:[],doc:{recompose(){}}};
 const env={read:char=>({PointSize:char.pointSize,Leading:char.leading,Tracking:char.tracking}),value:v=>v??null,compare:M.compare,bounds:()=>c.bounds,guard(){},progress(){}};return {c,context,env,chars};
}
test('bounded fit stops at first native non-overflow and preserves mixed-size proportions and full text',()=>{const x=fixture({initial:true});A.run(x.context,x.env);assert.equal(x.c.autoFit.ratio,.96);assert.equal(x.context.autoFit.groups[0].steps.length,2);assert.ok(Math.abs(x.chars[0].pointSize/x.chars[1].pointSize-1.5)<1e-12);assert.equal(x.c.frame.parentStory.contents,'가나');assert.equal(A.check(x.c,x.env.read,x.env.value,M.compare).equal,true);x.chars[0].tracking=19;assert.equal(A.check(x.c,x.env.read,x.env.value,M.compare).equal,false);});
test('subtitle limit and auto-leading remain strict; overflowing result is not approval',()=>{const x=fixture({role:'subtitle',threshold:.5,autoLeading:true});A.run(x.context,x.env);assert.equal(x.c.autoFit.ratio,.96);assert.equal(x.context.autoFit.groups[0].success,false);assert.equal(x.c.frame.parentStory.overflows,true);assert.equal(x.chars[0].leading,'Auto');assert.equal(x.chars[0].tracking,20);});
test('no overflow or TITLE means no typography write; unsafe policy stays unsupported',()=>{const x=fixture({threshold:1});A.run(x.context,x.env);assert.equal(x.c.autoFit,undefined);const title=fixture({role:'title'});A.run(title.context,title.env);assert.equal(title.c.autoFit,undefined);const bad=fixture();bad.c.textPolicy.mode='unknown';assert.throws(()=>A.run(bad.context,bad.env),/UNSUPPORTED/);});
test('BODY stories share one ratio and keep independently assigned text; forged adjustment is rejected',()=>{const x=fixture({threshold:.96}),y=fixture({threshold:.94});x.context.contentChecks.push(y.c);A.run(x.context,x.env);assert.equal(x.c.autoFit.ratio,.94);assert.equal(y.c.autoFit.ratio,.94);assert.equal(A.check({...x.c},x.env.read,x.env.value,M.compare).equal,true);assert.equal(A.check({...x.c,autoFit:{...x.c.autoFit}},x.env.read,x.env.value,M.compare).equal,false);});
test('content or geometry mutation during Recompose blocks fit',()=>{const x=fixture();x.context.doc.recompose=()=>{x.c.frame.parentStory.contents='누락';};assert.throws(()=>A.run(x.context,x.env),/content\/geometry/);});
